### ISSUE TITLE
Cannot pnpm build;  ELIFECYCLE  Command failed with exit code 1.

### ISSUE THREAD

**Issue by miali88** [HamedMP/CursorLens#2]
Following the docs/getting-started/installation, and up to step 5. The full logs are

`@MacBook-Pro-2 cursorlens % pnpm build

> cursor-analytics@0.1.0 build /Users/ma/Library/GH_COMM/CursorLens/CursorLens
> next build

  ▲ Next.js 14.2.5
  - Environments: .env

   Creating an optimized production build ...
 ✓ Compiled successfully
   Linting and checking validity of types  .Failed to compile.

src/app/logs/[id]/page.tsx
Type error: Page "src/app/logs/[id]/page.tsx" has an invalid "default" export:
  Type "LogDetailsProps" is not valid.

 ELIFECYCLE  Command failed with exit code 1.`

**Comment by HamedMP** [comment]
Thanks for reporting. I haven't had time to check the `build` command yet. Will reproduce it now and get back to you.

**Comment by HamedMP** [comment]
Can you pull now and see if it's fixed? I just pushed a fix and it worked on mine #d2b33ca222c6de4804da8a6573b7adb105b3e4d3

**Comment by miali88** [comment]
Issue fixed ✅, on the dev server. Just having issue with finding the API endpoint on Cursor settings, not seeing it on VSC extension, nor the website

**Comment by HamedMP** [comment]
You can find it in Models -> Override OpenAI Base URL

Make sure the toggle is ON if you are a Pro user. 

Then use any OAI model (`gpt-4o`, etc) so that OAI settings will be used. Cursor decides which provider is it based on the first part of the model name. 

<img width="1069" alt="image" src="https://github.com/user-attachments/assets/0735689f-f609-41b7-a965-214498cfe311">

I'm closing the issue as the original bug is fixed 🙌🏼
